FROM python:3.5

WORKDIR /app

ENV CRON_INTERVAL="* * * * *"
ENV KRAKEN_KEY=""
ENV KRAKEN_SECRET="" 

RUN apt-get update && apt-get install -y --no-install-recommends \
		cron

COPY . /app

RUN pip install -r requirements.txt

CMD ./cmd.sh